### ISSUE TITLE
WinRT Status

### ISSUE THREAD

**Issue by steerlink** [cocos2d/cocos2d-x-3rd-party-libs-src#101]
I've been reviewing the latest merge of the WinRT changes from @stammen and have a few questions.

1) Is it in a complete state or still a work in progress?
2) Is there a reason why some libraries use `"%VS140COMNTOOLS%vsvars32` and others use `"%VS120COMNTOOLS%vsvars32` (e.g. chipmunk vs zlib)?
3) Why is openssl not built by `build_winrt.bat`?

**Comment by minggo** [comment]
@stammen Could you please explain it?
Thanks.

**Comment by stammen** [comment]
@steerlink Unfortunately this pull request https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/pull/92 was from the wrong branch of the msopentech repo https://github.com/MSOpenTech/cocos2d-x-3rd-party-libs-src. I was working off of the v3-winrt-temp branch and @zilongshanren used the v3-winrt branch. I had not yet merged the two branchs. The main difference between the branchs is that the v3-winrt-temp branch has both the WIndows 10 UWP and Windows 8.1 scripts while the v3-winrt branch has mainly the Windows 8.1 scripts.

This is indeed a work in progress as I have not made a pull request to the main cocos2d-x-3rd-party-libs-src repo. I plan to spend some time in early April to clean up the code after the Microsoft Build conference.

Once my work is done, VS2015 will be required and everything will use "%VS140COMNTOOLS%vsvars32. This is because VS2015 can build both VS2013 (WIndows 8.1) and VS2015 (Windows 10 UWP) projects.

Hope this helps.

**Comment by steerlink** [comment]
@stammen Thanks for the update. I appreciate your work and I use it often. Please let me know if there is anyway I can help. I'd like to use this repo for keeping libraries updated across all the platforms. Having all the build scripts in one place would be ideal.

**Comment by stammen** [comment]
@steerlink I have updated this repo to build the Win10 UWP dependencies using https://github.com/Microsoft/vcpkg.

**Comment by steerlink** [comment]
Thanks @stammen. I'll check it out.
